# If BOT_TYPE = "rule-based", then use fixed questions.
# If set to any other value, use LLM to generate questions.
# Reviews are generated by LLM regardless of BOT_TYPE.
BOT_TYPE = "gpt"
MODEL = "gpt-4.1"
MAX_QUESTIONS = 5
MIN_QUESTIONS = 3

TEMPERATURE_INTERVIEW = 0.5
TEMPERATURE_RATING = 0.0
TEMPERATURE_REVIEW = 0.0
LANG = 'en'

SAVE_COMPLETED = False  # whether to save the completed interview or not

# special tokens for interview
CONTINUE_TOKEN = "[Wait_for_Response]"
END_TOKEN = "[End_of_Interview]"

# placeholders for prompts
PH_DIALOGUE = "[DIALOGUE]"
PH_NAME = "[PRODUCT_NAME]"
PH_REVIEW = "[REVIEW]"

# clean up log files
TIMEOUT_SECONDS = 1 * 60 * 60 # 1 hour
MAX_LOG_FILES = 1
LOG_DIR = "./data/logs/"

